import { Participant, EmploymentOutcome } from '../../core/domain/entities/Participant';
import { Enterprise, TrainingCohort } from '../../core/domain/entities/Enterprise';
import { Partnership, LoanRecord, SavingsGroup, BudgetOverview } from '../../core/domain/entities/Finance';
import { SafeguardingIncident, FeedbackTicket, ActionItem } from '../../core/domain/entities/Accountability';
import { LessonLearned, KnowledgeDocument, LearningAgendaQuestion, ReflectionMeeting } from '../../core/domain/entities/Learning';
import { Indicator, SurveyRound, OfflineSurveyItem } from '../../core/domain/entities/Evidence';
import { AuditLogEntry, GovernanceItem } from '../../core/domain/entities/System';
import { DEMO_USERS, User } from '../../core/domain/entities/User';

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'p-1',
    fullName: 'Almaz Tadesse',
    fayidaId: 'ET-FAY-98214301',
    phone: '+251 91 123 4567',
    sex: 'Female',
    age: 23,
    education: 'TVET Graduate',
    region: 'Oromia',
    woreda: 'Bishoftu',
    kebele: 'Kebele 02',
    disability: false,
    status: 'Employed',
    cohort: 'Cohort 1 - Agro-processing',
    registrationDate: '2025-11-12',
    enterpriseId: 'ent-1',
    assignedFieldOfficer: 'Yared Getachew',
  },
  {
    id: 'p-2',
    fullName: 'Dawit Bekele',
    fayidaId: 'ET-FAY-65239102',
    phone: '+251 92 345 6789',
    sex: 'Male',
    age: 26,
    education: 'Secondary',
    region: 'Amhara',
    woreda: 'Bahir Dar Zuria',
    kebele: 'Kebele 08',
    disability: false,
    status: 'Self-Employed',
    cohort: 'Cohort 2 - Metal & Woodworking',
    registrationDate: '2025-11-18',
    enterpriseId: 'ent-2',
    assignedFieldOfficer: 'Tigist Alemu',
  },
  {
    id: 'p-3',
    fullName: 'Hiwot Assefa',
    fayidaId: 'ET-FAY-77319084',
    phone: '+251 93 456 7890',
    sex: 'Female',
    age: 21,
    education: 'Primary',
    region: 'Sidama',
    woreda: 'Hawassa Zuria',
    kebele: 'Tula 01',
    disability: true,
    disabilityType: 'Hearing Impairment',
    status: 'In Training',
    cohort: 'Cohort 3 - Garment & Apparel',
    registrationDate: '2025-12-05',
    assignedFieldOfficer: 'Mulugeta T.',
  },
  {
    id: 'p-4',
    fullName: 'Chala Demisse',
    fayidaId: 'ET-FAY-88412093',
    phone: '+251 94 567 8901',
    sex: 'Male',
    age: 24,
    education: 'TVET Graduate',
    region: 'Oromia',
    woreda: 'Adama',
    kebele: 'Bole Kebele',
    disability: false,
    status: 'Employed',
    cohort: 'Cohort 1 - Agro-processing',
    registrationDate: '2025-10-20',
    enterpriseId: 'ent-3',
    assignedFieldOfficer: 'Yared Getachew',
  },
  {
    id: 'p-5',
    fullName: 'Selamawit Desta',
    fayidaId: 'ET-FAY-11293847',
    phone: '+251 91 678 9012',
    sex: 'Female',
    age: 22,
    education: 'University Degree',
    region: 'Addis Ababa',
    woreda: 'Bole',
    kebele: 'Woreda 03',
    disability: false,
    status: 'Employed',
    cohort: 'Cohort 4 - Digital Freelancing',
    registrationDate: '2025-11-01',
    enterpriseId: 'ent-4',
  },
  {
    id: 'p-6',
    fullName: 'Ahmed Mohammed',
    fayidaId: 'ET-FAY-55483920',
    phone: '+251 92 789 0123',
    sex: 'Male',
    age: 28,
    education: 'Secondary',
    region: 'Somali',
    woreda: 'Jijiga',
    kebele: 'Kebele 04',
    disability: false,
    status: 'Self-Employed',
    cohort: 'Cohort 2 - Livestock Value Chain',
    registrationDate: '2025-12-14',
    enterpriseId: 'ent-5',
  },
  {
    id: 'p-7',
    fullName: 'Genet Worku',
    fayidaId: 'ET-FAY-33291823',
    phone: '+251 93 890 1234',
    sex: 'Female',
    age: 25,
    education: 'TVET Graduate',
    region: 'Central Ethiopia',
    woreda: 'Hosanna',
    kebele: 'Kebele 01',
    disability: true,
    disabilityType: 'Mobility Impairment',
    status: 'In Training',
    cohort: 'Cohort 3 - Leather Works',
    registrationDate: '2026-01-10',
  },
  {
    id: 'p-8',
    fullName: 'Biruk Kebede',
    fayidaId: 'ET-FAY-99018274',
    phone: '+251 94 901 2345',
    sex: 'Male',
    age: 20,
    education: 'Primary',
    region: 'Amhara',
    woreda: 'Dessie',
    kebele: 'Kebele 05',
    disability: false,
    status: 'Enrolled',
    cohort: 'Cohort 5 - Renewable Energy Assembly',
    registrationDate: '2026-01-15',
  },
  {
    id: 'p-9',
    fullName: 'Meron Hailu',
    fayidaId: 'ET-FAY-44582910',
    phone: '+251 91 012 3456',
    sex: 'Female',
    age: 27,
    education: 'TVET Graduate',
    region: 'Tigray',
    woreda: 'Mekelle',
    kebele: 'Kedamay Weyane',
    disability: false,
    status: 'Employed',
    cohort: 'Cohort 1 - Food Processing',
    registrationDate: '2025-10-05',
  },
  {
    id: 'p-10',
    fullName: 'Kidus Solomon',
    fayidaId: 'ET-FAY-22910482',
    phone: '+251 92 123 7890',
    sex: 'Male',
    age: 23,
    education: 'Secondary',
    region: 'Dire Dawa',
    woreda: 'Sabian',
    kebele: 'Kebele 02',
    disability: false,
    status: 'Employed',
    cohort: 'Cohort 4 - Logistics & Warehousing',
    registrationDate: '2025-11-25',
  },
  {
    id: 'p-11',
    fullName: 'Tigist Mengistu',
    fayidaId: 'ET-FAY-33019482',
    phone: '+251 93 234 8901',
    sex: 'Female',
    age: 24,
    education: 'TVET Graduate',
    region: 'Oromia',
    woreda: 'Jimma',
    kebele: 'Mendera Koch',
    disability: false,
    status: 'Self-Employed',
    cohort: 'Cohort 2 - Coffee Nursery & Agronomy',
    registrationDate: '2025-11-20',
  },
  {
    id: 'p-12',
    fullName: 'Yonas Tesfaye',
    fayidaId: 'ET-FAY-88127394',
    phone: '+251 94 345 9012',
    sex: 'Male',
    age: 22,
    education: 'Secondary',
    region: 'Sidama',
    woreda: 'Yirgalem',
    kebele: 'Kebele 03',
    disability: true,
    disabilityType: 'Visual Impairment (Low Vision)',
    status: 'In Training',
    cohort: 'Cohort 3 - Poultry & Feed Production',
    registrationDate: '2026-01-08',
  },
  // Add generated 38 more realistic participants to reach 50
  ...Array.from({ length: 38 }, (_, i) => {
    const idx = i + 13;
    const isFemale = idx % 2 === 0;
    const regions = ['Oromia', 'Amhara', 'Sidama', 'Somali', 'Central Ethiopia', 'Addis Ababa', 'Tigray', 'Dire Dawa'];
    const statuses: Participant['status'][] = ['Employed', 'Self-Employed', 'In Training', 'Enrolled', 'Graduated'];
    const firstNames = isFemale 
      ? ['Bethlehem', 'Meseret', 'Frehiwot', 'Rahel', 'Aster', 'Hanan', 'Birtukan', 'Lulit', 'Marta', 'Fikirte', 'Zufan', 'Hirut']
      : ['Solomon', 'Henok', 'Robel', 'Kassahun', 'Tewodros', 'Ephrem', 'Binyam', 'Getnet', 'Natnael', 'Fikru', 'Alemayehu', 'Girma'];
    const lastNames = ['Alemu', 'Gebre', 'Mengistu', 'Girma', 'Kassa', 'Woldemariam', 'Belay', 'Worku', 'Abebe', 'Desta', 'Negash', 'Tilahun'];
    const fn = firstNames[idx % firstNames.length];
    const ln = lastNames[(idx * 3) % lastNames.length];
    const region = regions[idx % regions.length];
    const hasDisability = idx % 7 === 0;
    return {
      id: `p-${idx}`,
      fullName: `${fn} ${ln}`,
      fayidaId: `ET-FAY-${90000000 + idx * 137}`,
      phone: `+251 9${(idx % 4) + 1} ${100 + idx} ${1000 + idx * 7}`,
      sex: isFemale ? 'Female' : 'Male',
      age: 19 + (idx % 11),
      education: (['Secondary', 'TVET Graduate', 'Primary', 'University Degree'] as const)[idx % 4],
      region,
      woreda: `Woreda ${((idx % 5) + 1)}`,
      kebele: `Kebele 0${((idx % 8) + 1)}`,
      disability: hasDisability,
      disabilityType: hasDisability ? 'Hearing / Mobility Assistance' : undefined,
      status: statuses[idx % statuses.length],
      cohort: `Cohort ${(idx % 4) + 1} - Enterprise Skills`,
      registrationDate: `2025-1${(idx % 3) + 0}-${10 + (idx % 18)}`,
    } as Participant;
  })
];

export const INITIAL_EMPLOYMENT_OUTCOMES: EmploymentOutcome[] = [
  {
    id: 'emp-1',
    participantId: 'p-1',
    participantName: 'Almaz Tadesse',
    sex: 'Female',
    region: 'Oromia',
    type: 'Wage Employment',
    jobTitle: 'Quality Control Technician',
    employerOrBusiness: 'Abyssinia Agro Processing PLC',
    sector: 'Agribusiness',
    monthlyIncomeEtb: 7800,
    contractType: 'Permanent',
    verified: true,
    verificationDate: '2026-01-10',
    startDate: '2025-12-01',
  },
  {
    id: 'emp-2',
    participantId: 'p-2',
    participantName: 'Dawit Bekele',
    sex: 'Male',
    region: 'Amhara',
    type: 'Self-Employment',
    jobTitle: 'Lead Artisan & Workshop Owner',
    employerOrBusiness: 'Bahir Wood & Metal Works',
    sector: 'Construction',
    monthlyIncomeEtb: 9500,
    contractType: 'Permanent',
    verified: true,
    verificationDate: '2026-01-15',
    startDate: '2025-12-10',
  },
  {
    id: 'emp-3',
    participantId: 'p-4',
    participantName: 'Chala Demisse',
    sex: 'Male',
    region: 'Oromia',
    type: 'Wage Employment',
    jobTitle: 'Machine Operator',
    employerOrBusiness: 'Adama Food Products SC',
    sector: 'Agribusiness',
    monthlyIncomeEtb: 6500,
    contractType: 'Contractual (6M+)',
    verified: true,
    verificationDate: '2026-01-20',
    startDate: '2025-11-15',
  },
  {
    id: 'emp-4',
    participantId: 'p-5',
    participantName: 'Selamawit Desta',
    sex: 'Female',
    region: 'Addis Ababa',
    type: 'Wage Employment',
    jobTitle: 'Junior Data Analyst',
    employerOrBusiness: 'AfroTech Solutions',
    sector: 'Digital & ICT',
    monthlyIncomeEtb: 14500,
    contractType: 'Permanent',
    verified: true,
    verificationDate: '2026-02-01',
    startDate: '2025-12-01',
  },
  {
    id: 'emp-5',
    participantId: 'p-6',
    participantName: 'Ahmed Mohammed',
    sex: 'Male',
    region: 'Somali',
    type: 'Micro-Enterprise',
    jobTitle: 'Livestock Fodder Trader',
    employerOrBusiness: 'Jijiga Green Fodder Hub',
    sector: 'Agribusiness',
    monthlyIncomeEtb: 8200,
    contractType: 'Permanent',
    verified: false,
    startDate: '2026-01-05',
  },
  {
    id: 'emp-6',
    participantId: 'p-9',
    participantName: 'Meron Hailu',
    sex: 'Female',
    region: 'Tigray',
    type: 'Wage Employment',
    jobTitle: 'Bakery Supervisor',
    employerOrBusiness: 'Mekelle Heritage Foods',
    sector: 'Hospitality',
    monthlyIncomeEtb: 7200,
    contractType: 'Contractual (6M+)',
    verified: true,
    verificationDate: '2026-02-10',
    startDate: '2025-11-20',
  },
  {
    id: 'emp-7',
    participantId: 'p-10',
    participantName: 'Kidus Solomon',
    sex: 'Male',
    region: 'Dire Dawa',
    type: 'Wage Employment',
    jobTitle: 'Inventory Clerk',
    employerOrBusiness: 'Dire Freight & Logistics',
    sector: 'Retail/Services',
    monthlyIncomeEtb: 6900,
    contractType: 'Contractual (6M+)',
    verified: true,
    verificationDate: '2026-01-28',
    startDate: '2025-12-15',
  },
  {
    id: 'emp-8',
    participantId: 'p-11',
    participantName: 'Tigist Mengistu',
    sex: 'Female',
    region: 'Oromia',
    type: 'Self-Employment',
    jobTitle: 'Specialty Coffee Roaster',
    employerOrBusiness: 'Jimma Aroma Micro-Roastery',
    sector: 'Agribusiness',
    monthlyIncomeEtb: 11000,
    contractType: 'Permanent',
    verified: true,
    verificationDate: '2026-02-05',
    startDate: '2025-12-10',
  }
];

export const INITIAL_ENTERPRISES: Enterprise[] = [
  {
    id: 'ent-1',
    name: 'Abyssinia Agro Processing PLC',
    registrationNumber: 'OR-BSH-2024-0012',
    ownerName: 'Kebede Haile',
    ownerSex: 'Male',
    ownerAge: 32,
    fayidaId: 'ET-FAY-91028345',
    phone: '+251 91 222 3344',
    sector: 'Agribusiness',
    tier: 'Small (6-15)',
    region: 'Oromia',
    woreda: 'Bishoftu',
    employeesCount: 14,
    youthEmployeesCount: 11,
    femaleEmployeesCount: 8,
    monthlyRevenueEtb: 380000,
    loanReceivedEtb: 250000,
    supportReceived: ['Technical Mentorship', 'Equipment Grant', 'BDS Training'],
    status: 'Active',
    establishedDate: '2023-04-15',
  },
  {
    id: 'ent-2',
    name: 'Bahir Wood & Metal Works Cooperative',
    registrationNumber: 'AM-BDR-2024-0891',
    ownerName: 'Dawit Bekele',
    ownerSex: 'Male',
    ownerAge: 26,
    fayidaId: 'ET-FAY-65239102',
    phone: '+251 92 345 6789',
    sector: 'Construction',
    tier: 'Micro (3-5)',
    region: 'Amhara',
    woreda: 'Bahir Dar Zuria',
    employeesCount: 5,
    youthEmployeesCount: 5,
    femaleEmployeesCount: 2,
    monthlyRevenueEtb: 120000,
    loanReceivedEtb: 100000,
    supportReceived: ['Toolkits Grant', 'Financial Literacy'],
    status: 'Scaling',
    establishedDate: '2024-01-10',
  },
  {
    id: 'ent-3',
    name: 'Hawassa Eco-Garments Hub',
    registrationNumber: 'SD-HAW-2023-1120',
    ownerName: 'Hirut Kassaye',
    ownerSex: 'Female',
    ownerAge: 29,
    fayidaId: 'ET-FAY-48192043',
    phone: '+251 93 444 5566',
    sector: 'Textile & Garments',
    tier: 'Medium (16+)',
    region: 'Sidama',
    woreda: 'Hawassa City',
    employeesCount: 24,
    youthEmployeesCount: 20,
    femaleEmployeesCount: 18,
    monthlyRevenueEtb: 540000,
    loanReceivedEtb: 450000,
    supportReceived: ['Market Linkage to Industrial Park', 'Quality Certification BDS'],
    status: 'Active',
    establishedDate: '2022-09-18',
  },
  {
    id: 'ent-4',
    name: 'AfroTech Innovations Lab',
    registrationNumber: 'AA-BOL-2024-3341',
    ownerName: 'Binyam Assefa',
    ownerSex: 'Male',
    ownerAge: 27,
    fayidaId: 'ET-FAY-77192039',
    phone: '+251 91 555 6677',
    sector: 'Digital & ICT',
    tier: 'Micro (3-5)',
    region: 'Addis Ababa',
    woreda: 'Bole',
    employeesCount: 4,
    youthEmployeesCount: 4,
    femaleEmployeesCount: 2,
    monthlyRevenueEtb: 190000,
    loanReceivedEtb: 150000,
    supportReceived: ['Coworking Voucher', 'Cloud Infrastructure Subsidy'],
    status: 'Scaling',
    establishedDate: '2024-03-01',
  },
  {
    id: 'ent-5',
    name: 'Rift Valley Organic Honey & Bee Products',
    registrationNumber: 'OR-ZWY-2023-0492',
    ownerName: 'Fatuma Hassen',
    ownerSex: 'Female',
    ownerAge: 28,
    fayidaId: 'ET-FAY-33910283',
    phone: '+251 94 666 7788',
    sector: 'Agribusiness',
    tier: 'Small (6-15)',
    region: 'Oromia',
    woreda: 'Ziway',
    employeesCount: 9,
    youthEmployeesCount: 8,
    femaleEmployeesCount: 6,
    monthlyRevenueEtb: 280000,
    loanReceivedEtb: 200000,
    supportReceived: ['Modern Beehive Package', 'Export Quality Testing'],
    status: 'Active',
    establishedDate: '2023-06-22',
  },
  // Add additional enterprises up to 25
  ...Array.from({ length: 20 }, (_, i) => {
    const idx = i + 6;
    const isFemale = idx % 2 === 0;
    const sectors: Enterprise['sector'][] = [
      'Agribusiness', 'Textile & Garments', 'Leather & Footwear', 'Digital & ICT', 'Construction', 'Hospitality & Tourism'
    ];
    const regions = ['Oromia', 'Amhara', 'Sidama', 'Somali', 'Central Ethiopia', 'Addis Ababa', 'Tigray', 'Dire Dawa'];
    const names = [
      'Nile Artisan Leather Craft', 'Somali Pastoral Dairy Hub', 'Gondar Heritage Weaving', 'Tigray Solar Assembly',
      'Dire Logistics Express', 'SNNP Fruit Processing Co', 'Bole Urban Hydroponics', 'Adama Precision Auto Care',
      'Yirgalem Coffee Washing Station', 'Bale Natural Oils Extraction', 'Dessie Metal Fabricators', 'Awash Renewable Tech'
    ];
    return {
      id: `ent-${idx}`,
      name: names[idx % names.length] + ` (Unit ${idx})`,
      registrationNumber: `REG-2024-00${100 + idx}`,
      ownerName: isFemale ? `W/ro Aster ${['Mulu', 'Girma', 'Kassa', 'Taye'][idx % 4]}` : `Ato Daniel ${['Bekele', 'Kebede', 'Hailu'][idx % 3]}`,
      ownerSex: isFemale ? 'Female' : 'Male',
      ownerAge: 24 + (idx % 15),
      fayidaId: `ET-FAY-${81000000 + idx * 293}`,
      phone: `+251 9${(idx % 4) + 1} 333 ${4000 + idx}`,
      sector: sectors[idx % sectors.length],
      tier: (['Nano (1-2)', 'Micro (3-5)', 'Small (6-15)'] as const)[idx % 3],
      region: regions[idx % regions.length],
      woreda: `Zone ${((idx % 3) + 1)} Woreda`,
      employeesCount: 3 + (idx % 9),
      youthEmployeesCount: 2 + (idx % 8),
      femaleEmployeesCount: 1 + (idx % 5),
      monthlyRevenueEtb: 85000 + idx * 12000,
      loanReceivedEtb: 50000 + (idx % 4) * 50000,
      supportReceived: ['Seed Grant', 'Mentorship'],
      status: (['Active', 'Scaling', 'Struggling'] as const)[idx % 3 === 0 ? 1 : 0],
      establishedDate: `2024-0${(idx % 8) + 1}-10`,
    } as Enterprise;
  })
];

export const INITIAL_TRAINING_COHORTS: TrainingCohort[] = [
  {
    id: 'tr-1',
    code: 'TRN-2025-AGRO-01',
    title: 'Modern Horticulture & Agro-Processing Value Addition',
    provider: 'Tegbare-Id Polytechnic College',
    sector: 'Agribusiness',
    region: 'Addis Ababa',
    woreda: 'Yeka',
    startDate: '2025-09-01',
    endDate: '2025-11-30',
    enrolledTotal: 45,
    enrolledFemale: 26,
    graduatedTotal: 42,
    graduatedFemale: 25,
    status: 'Completed',
    attendanceRatePercent: 94.2,
    curriculumHours: 240,
  },
  {
    id: 'tr-2',
    code: 'TRN-2025-GAR-02',
    title: 'Industrial Sewing Machine Operation & Quality Inspection',
    provider: 'Hawassa TVET Institute',
    sector: 'Textile & Garments',
    region: 'Sidama',
    woreda: 'Hawassa',
    startDate: '2025-10-15',
    endDate: '2026-01-15',
    enrolledTotal: 60,
    enrolledFemale: 48,
    graduatedTotal: 57,
    graduatedFemale: 46,
    status: 'Completed',
    attendanceRatePercent: 96.0,
    curriculumHours: 320,
  },
  {
    id: 'tr-3',
    code: 'TRN-2026-DIG-03',
    title: 'Digital Micro-work, E-commerce, & Remote Data Management',
    provider: 'Adama Science & Tech TVET Center',
    sector: 'Digital & ICT',
    region: 'Oromia',
    woreda: 'Adama',
    startDate: '2026-01-05',
    endDate: '2026-04-05',
    enrolledTotal: 50,
    enrolledFemale: 27,
    graduatedTotal: 0,
    graduatedFemale: 0,
    status: 'In Progress',
    attendanceRatePercent: 91.5,
    curriculumHours: 200,
  },
  {
    id: 'tr-4',
    code: 'TRN-2026-SOLAR-04',
    title: 'Solar PV Installation, Maintenance & Water Pumping',
    provider: 'Bahir Dar Polytechnic Institute',
    sector: 'Renewable Energy',
    region: 'Amhara',
    woreda: 'Bahir Dar',
    startDate: '2026-02-01',
    endDate: '2026-05-01',
    enrolledTotal: 40,
    enrolledFemale: 16,
    graduatedTotal: 0,
    graduatedFemale: 0,
    status: 'In Progress',
    attendanceRatePercent: 88.7,
    curriculumHours: 280,
  },
  {
    id: 'tr-5',
    code: 'TRN-2026-LEATH-05',
    title: 'Footwear Pattern Making & Leather Goods Assembly',
    provider: 'Ethiopian Leather Industry Development Institute (LIDI)',
    sector: 'Leather & Footwear',
    region: 'Oromia',
    woreda: 'Bishoftu',
    startDate: '2026-03-15',
    endDate: '2026-06-15',
    enrolledTotal: 35,
    enrolledFemale: 19,
    graduatedTotal: 0,
    graduatedFemale: 0,
    status: 'Planning',
    attendanceRatePercent: 0,
    curriculumHours: 300,
  }
];

export const INITIAL_PARTNERSHIPS: Partnership[] = [
  {
    id: 'part-1',
    partnerName: 'Oromia Credit & Saving S.C. (Siinqee Bank / OCSSCO)',
    type: 'Microfinance Institution',
    region: 'Oromia',
    contactPerson: 'Tolessa Gemechu',
    email: 't.gemechu@siinqeebank.com.et',
    phone: '+251 11 557 1234',
    mouSignedDate: '2025-06-15',
    expiryDate: '2027-06-14',
    focusArea: 'Youth entrepreneurship concessionary loans & VSLA account linkages',
    activeProjectsCount: 4,
    status: 'Active',
  },
  {
    id: 'part-2',
    partnerName: 'Amhara Credit & Saving Institution (ACSI / Tsedey Bank)',
    type: 'Microfinance Institution',
    region: 'Amhara',
    contactPerson: 'Moges Yallew',
    email: 'm.yallew@tsedeybank.et',
    phone: '+251 58 220 9876',
    mouSignedDate: '2025-07-01',
    expiryDate: '2027-06-30',
    focusArea: 'Rural agri-business micro-credit guarantees',
    activeProjectsCount: 3,
    status: 'Active',
  },
  {
    id: 'part-3',
    partnerName: 'Hawassa Industrial Park Investors Association',
    type: 'Private Employer',
    region: 'Sidama',
    contactPerson: 'Belachew Mekuria',
    email: 'info@hipia-ethiopia.org',
    phone: '+251 46 220 1122',
    mouSignedDate: '2025-08-10',
    expiryDate: '2026-08-09',
    focusArea: 'Direct job placement for certified TVET apparel trainees',
    activeProjectsCount: 2,
    status: 'Active',
  },
  {
    id: 'part-4',
    partnerName: 'Ministry of Labor and Skills (MOLS)',
    type: 'Government Bureau',
    region: 'National / Federal',
    contactPerson: 'Dr. Teshale Berecha',
    email: 'contact@mols.gov.et',
    phone: '+251 11 551 7733',
    mouSignedDate: '2025-05-01',
    expiryDate: '2028-04-30',
    focusArea: 'National occupational standards, TVET accreditation, and Fayida ID integration',
    activeProjectsCount: 5,
    status: 'Active',
  },
  {
    id: 'part-5',
    partnerName: 'National Enterprise Telecommunications',
    type: 'Private Employer',
    region: 'National / Federal',
    contactPerson: 'Frehiwot Tamru Office',
    email: 'telecom.enterprise@ethiotelecom.et',
    phone: '+251 11 551 5700',
    mouSignedDate: '2025-05-20',
    expiryDate: '2028-05-19',
    focusArea: 'Telebirr merchant integration, digital MEAL MIS hosting & SMS gateway',
    activeProjectsCount: 6,
    status: 'Active',
  }
];

export const INITIAL_LOANS: LoanRecord[] = [
  {
    id: 'loan-1',
    loanReference: 'LN-2025-OC-0192',
    beneficiaryName: 'Almaz Tadesse',
    beneficiaryType: 'Individual Youth',
    sex: 'Female',
    fayidaId: 'ET-FAY-98214301',
    mfiPartner: 'Siinqee Bank (OCSSCO)',
    region: 'Oromia',
    woreda: 'Bishoftu',
    amountRequestedEtb: 65000,
    amountDisbursedEtb: 60000,
    interestRatePercent: 8.5,
    disbursementDate: '2025-11-25',
    dueDate: '2026-11-24',
    amountRepaidEtb: 15000,
    repaymentStatus: 'Current',
    purpose: 'Procurement of stainless fruit pulping unit & bottling jars',
  },
  {
    id: 'loan-2',
    loanReference: 'LN-2025-AC-0842',
    beneficiaryName: 'Bahir Wood & Metal Works Cooperative',
    beneficiaryType: 'Enterprise / Cooperative',
    sex: 'Male',
    fayidaId: 'ET-FAY-65239102',
    mfiPartner: 'Tsedey Bank (ACSI)',
    region: 'Amhara',
    woreda: 'Bahir Dar',
    amountRequestedEtb: 120000,
    amountDisbursedEtb: 100000,
    interestRatePercent: 9.0,
    disbursementDate: '2025-12-05',
    dueDate: '2027-06-04',
    amountRepaidEtb: 22500,
    repaymentStatus: 'Current',
    purpose: 'Electric arc welding generators and safety equipment',
  },
  {
    id: 'loan-3',
    loanReference: 'LN-2026-OM-0041',
    beneficiaryName: 'Hiwot Assefa',
    beneficiaryType: 'Individual Youth',
    sex: 'Female',
    fayidaId: 'ET-FAY-77319084',
    mfiPartner: 'Omo Microfinance',
    region: 'Sidama',
    woreda: 'Hawassa',
    amountRequestedEtb: 40000,
    amountDisbursedEtb: 40000,
    interestRatePercent: 7.5,
    disbursementDate: '2026-01-12',
    dueDate: '2027-01-11',
    amountRepaidEtb: 0,
    repaymentStatus: 'Grace Period',
    purpose: 'Heavy-duty industrial overlock sewing machine purchase',
  },
  {
    id: 'loan-4',
    loanReference: 'LN-2025-DB-0319',
    beneficiaryName: 'Mekelle Youth Food Hub',
    beneficiaryType: 'Enterprise / Cooperative',
    sex: 'Female',
    fayidaId: 'ET-FAY-44582910',
    mfiPartner: 'Dedebit Credit & Saving (DECSI)',
    region: 'Tigray',
    woreda: 'Mekelle',
    amountRequestedEtb: 150000,
    amountDisbursedEtb: 150000,
    interestRatePercent: 8.0,
    disbursementDate: '2025-10-30',
    dueDate: '2026-10-29',
    amountRepaidEtb: 50000,
    repaymentStatus: 'Current',
    purpose: 'Commercial bakery oven and working capital',
  }
];

export const INITIAL_SAVINGS_GROUPS: SavingsGroup[] = [
  {
    id: 'svg-1',
    groupName: 'Biftu Gudina Youth VSLA',
    code: 'VSLA-OR-BSH-01',
    region: 'Oromia',
    woreda: 'Bishoftu',
    totalMembers: 25,
    femaleMembers: 18,
    youthMembers: 25,
    establishedDate: '2025-08-01',
    totalSavingsMobilizedEtb: 185000,
    loansIssuedInternalEtb: 142000,
    bankLinkageEstablished: true,
    linkedBankOrMfi: 'Siinqee Bank Bishoftu Branch',
    status: 'Active',
  },
  {
    id: 'svg-2',
    groupName: 'Selam Youth Savings Union',
    code: 'VSLA-AM-BDR-04',
    region: 'Amhara',
    woreda: 'Bahir Dar',
    totalMembers: 30,
    femaleMembers: 20,
    youthMembers: 30,
    establishedDate: '2025-09-15',
    totalSavingsMobilizedEtb: 220000,
    loansIssuedInternalEtb: 190000,
    bankLinkageEstablished: true,
    linkedBankOrMfi: 'Tsedey Bank Bahir Dar Branch',
    status: 'Graduating to SACCO',
  },
  {
    id: 'svg-3',
    groupName: 'Tula Women & Youth Circle',
    code: 'VSLA-SD-HAW-02',
    region: 'Sidama',
    woreda: 'Hawassa Zuria',
    totalMembers: 22,
    femaleMembers: 22,
    youthMembers: 22,
    establishedDate: '2025-10-20',
    totalSavingsMobilizedEtb: 140000,
    loansIssuedInternalEtb: 95000,
    bankLinkageEstablished: false,
    status: 'Active',
  }
];

export const INITIAL_BUDGET: BudgetOverview = {
  totalBudgetEtb: 5300000, // 5.3M ETB matching demo
  totalDisbursedEtb: 2120000, // 2.12M ETB disbursed
  totalCommittedEtb: 1450000,
  remainingEtb: 1730000,
  burnRatePercent: 40.0,
  components: [
    {
      name: 'Component 1: Youth Skills & TVET Partnerships',
      allocatedEtb: 1800000,
      spentEtb: 820000,
      variancePercent: 45.5,
    },
    {
      name: 'Component 2: Enterprise Grants & BDS Mentorship',
      allocatedEtb: 1600000,
      spentEtb: 680000,
      variancePercent: 42.5,
    },
    {
      name: 'Component 3: MFI Concessionary Loan Guarantees',
      allocatedEtb: 1100000,
      spentEtb: 410000,
      variancePercent: 37.2,
    },
    {
      name: 'Component 4: Digital MEAL MIS & Safeguarding Operations',
      allocatedEtb: 800000,
      spentEtb: 210000,
      variancePercent: 26.2,
    }
  ]
};

export const INITIAL_SAFEGUARDING_INCIDENTS: SafeguardingIncident[] = [
  {
    id: 'sg-1',
    incidentCode: 'SG-2026-001',
    title: 'Workplace safety equipment deficiency at processing partner site',
    category: 'Unsafe Working Conditions',
    severity: 'Medium',
    status: 'Action Plan Underway',
    reportedDate: '2026-01-18',
    region: 'Oromia',
    woreda: 'Bishoftu',
    isConfidential: false,
    assignedInvestigator: 'Almaz Tadesse',
    targetResolutionDate: '2026-02-28',
    summary: 'Youth trainees reported lack of certified protective heat gloves and eye goggles during steam boiler operation.',
    actionsTaken: [
      'Site inspection conducted on Jan 22',
      'PPE delivery mandate issued to partner firm',
      'Refresher safety training delivered on Feb 05'
    ],
  },
  {
    id: 'sg-2',
    incidentCode: 'SG-2026-002',
    title: 'Confidential: Alleged intimidation by subcontractor supervisor',
    category: 'Workplace Harassment / Bullying',
    severity: 'High',
    status: 'Investigation Active',
    reportedDate: '2026-01-25',
    region: 'Sidama',
    woreda: 'Hawassa',
    isConfidential: true,
    assignedInvestigator: 'Lead Safeguarding Specialist (PMU)',
    targetResolutionDate: '2026-02-15',
    summary: 'Female intern reported repeated verbal intimidation regarding shift scheduling and performance appraisals.',
    actionsTaken: [
      'Immediate interim reassignment of participant to alternative department',
      'Formal hearing with HR panel scheduled'
    ],
  },
  {
    id: 'sg-3',
    incidentCode: 'SG-2025-014',
    title: 'Inaccessible training venue entrance for participant with wheelchair',
    category: 'Discrimination / Exclusion',
    severity: 'Low',
    status: 'Resolved & Closed',
    reportedDate: '2025-12-02',
    region: 'Addis Ababa',
    woreda: 'Yeka',
    isConfidential: false,
    assignedInvestigator: 'Dawit Bekele',
    targetResolutionDate: '2025-12-16',
    summary: 'Wheelchair access ramp was obstructed by construction debris at TVET entrance.',
    actionsTaken: [
      'Permanent concrete ramp cleared and regraded with handrails installed',
      'Accessibility audit completed across all 6 training halls'
    ],
  }
];

export const INITIAL_FEEDBACK_TICKETS: FeedbackTicket[] = [
  {
    id: 'fb-1',
    ticketNumber: 'FB-HOT-2026-042',
    channel: 'Toll-Free Hotline (8080)',
    category: 'Payment Delay',
    senderName: 'Robel Kebede',
    isAnonymous: false,
    phoneOrContact: '+251 91 190 2834',
    region: 'Amhara',
    dateReceived: '2026-02-02',
    message: 'Training transport stipend for Cohort 2 January attendance has not reached telebirr wallet yet.',
    status: 'Under Review',
    slaBreach: false,
  },
  {
    id: 'fb-2',
    ticketNumber: 'FB-SMS-2026-098',
    channel: 'SMS Gateway',
    category: 'Selection Transparency',
    senderName: 'Anonymous Community Youth',
    isAnonymous: true,
    region: 'Oromia',
    dateReceived: '2026-02-04',
    message: 'Can you clarify criteria used for agribusiness toolkits distribution in Woreda 03?',
    status: 'Response Dispatched',
    resolutionSummary: 'Automated and officer SMS reply sent detailing eligibility criteria and public scoring rubric.',
    slaBreach: false,
  },
  {
    id: 'fb-3',
    ticketNumber: 'FB-FLD-2026-015',
    channel: 'Field Helpdesk / Box',
    category: 'Service Quality',
    senderName: 'Genet Worku',
    isAnonymous: false,
    phoneOrContact: '+251 93 890 1234',
    region: 'Central Ethiopia',
    dateReceived: '2026-01-20',
    message: 'Request for sign-language interpreter during technical modules on precision cutting.',
    status: 'Resolved',
    resolutionSummary: 'Dedicated certified sign interpreter contracted for all practical workshop sessions.',
    slaBreach: false,
  }
];

export const INITIAL_ACTION_ITEMS: ActionItem[] = [
  {
    id: 'act-1',
    title: 'Formalize Fayida ID biometric validation API endpoint with NIDP',
    description: 'Ensure automated deduplication check during batch youth registration.',
    source: 'Internal Audit',
    assignedTo: 'Dawit Bekele',
    department: 'Field Delivery',
    region: 'National / Federal',
    dueDate: '2026-03-10',
    priority: 'High',
    status: 'In Progress',
  },
  {
    id: 'act-2',
    title: 'Standardize quarterly loan repayment data exchange with Siinqee Bank',
    description: 'Establish secure SFTP / REST bridge for automated loan ledger updates.',
    source: 'Donor Joint Review',
    assignedTo: 'Bethlehem Alemu',
    department: 'Finance',
    region: 'Oromia',
    dueDate: '2026-03-25',
    priority: 'Medium',
    status: 'Open',
  },
  {
    id: 'act-3',
    title: 'Complete disability accessibility checklist across Hawassa TVET facilities',
    description: 'Verify tactile paving, ramp gradients, and accessible sanitary blocks.',
    source: 'MEAL Field Visit',
    assignedTo: 'Almaz Tadesse',
    department: 'Operations',
    region: 'Sidama',
    dueDate: '2026-02-28',
    priority: 'High',
    status: 'In Progress',
  }
];

export const INITIAL_LESSONS_LEARNED: LessonLearned[] = [
  {
    id: 'lsn-1',
    code: 'LL-2025-01',
    title: 'Telebirr stipend direct disbursement reduced participant drop-outs by 28%',
    thematicArea: 'Digital Literacy',
    context: 'In earlier phases, physical cash distributions caused travel delays and attendance gaps.',
    challengeFaced: 'Rural youth had to travel up to 30km to woreda capital to collect per diems.',
    lessonExtracted: 'Integrating digital mobile money wallets with attendance tracking creates instantaneous, transparent financial incentive.',
    practicalRecommendation: 'Mandate digital wallet registration at onboarding and integrate telebirr bulk disbursement API directly into MIS attendance module.',
    submittedBy: 'Almaz Tadesse',
    region: 'Oromia',
    dateDocumented: '2025-12-10',
    validationStatus: 'Approved for Scaling',
    tags: ['Telebirr', 'Cashless', 'Attendance', 'Retention'],
  },
  {
    id: 'lsn-2',
    code: 'LL-2026-02',
    title: 'Pre-negotiated MFI interest subsidies accelerate youth enterprise loan absorption',
    thematicArea: 'MFI Linkage',
    context: 'Commercial microfinance interest rates at 16-19% discouraged young entrepreneurs from taking risk.',
    challengeFaced: 'High loan collateral and interest hurdles for nascent youth cooperatives.',
    lessonExtracted: 'When programme guarantees first-loss capital and caps effective borrower rate at 8%, borrowing appetite tripled.',
    practicalRecommendation: 'Structure tri-partite agreements with partner MFIs (Siinqee, ACSI, DECSI) with explicit risk-sharing reserves.',
    submittedBy: 'Bethlehem Alemu',
    region: 'Amhara',
    dateDocumented: '2026-01-20',
    validationStatus: 'Peer Reviewed',
    tags: ['Microfinance', 'Guarantee Fund', 'Interest Subsidy', 'MSME'],
  }
];

export const INITIAL_KNOWLEDGE_DOCS: KnowledgeDocument[] = [
  {
    id: 'kd-1',
    title: 'Enterprise MEAL Framework & Performance Indicator Reference Sheets (PIRS)',
    category: 'Policy & Manual',
    author: 'PMU MEAL Directorate',
    publishedDate: '2025-06-15',
    fileSizeMb: 4.8,
    fileFormat: 'PDF',
    downloadCount: 142,
    description: 'Comprehensive indicator definitions, calculation methodologies, data sources, and reporting timelines for all programme logframe KPIs.',
  },
  {
    id: 'kd-2',
    title: 'Safeguarding & PSEA Standard Operating Procedures (SOP) Ethiopia',
    category: 'Policy & Manual',
    author: 'Ethics & Compliance Unit',
    publishedDate: '2025-08-01',
    fileSizeMb: 2.3,
    fileFormat: 'PDF',
    downloadCount: 89,
    description: 'Protocols for handling sensitive disclosures, incident escalation matrices, survivor-centered assistance, and confidentiality guarantees.',
  },
  {
    id: 'kd-3',
    title: 'Youth Agribusiness Incubation Best Practices â" Lessons from Oromia & Sidama',
    category: 'Case Study',
    author: 'Enterprise Development Team',
    publishedDate: '2025-11-20',
    fileSizeMb: 6.1,
    fileFormat: 'PDF',
    downloadCount: 76,
    description: 'Comparative review of 12 youth-led honey, poultry, and vegetable value chain enterprises supported through grant matching.',
  }
];

export const INITIAL_LEARNING_AGENDA: LearningAgendaQuestion[] = [
  {
    id: 'la-1',
    pillar: 'Youth Retention',
    questionText: 'What post-placement mentorship interventions have the highest correlation with 6-month job retention among female TVET graduates?',
    leadInvestigator: 'Almaz Tadesse (PMU)',
    status: 'Data Gathering',
    evidenceCollectedSummary: 'Data collected from 180 graduates in Hawassa and Bishoftu indicates peer WhatsApp cohorts increase retention by 34%.',
    lastUpdated: '2026-02-01',
  },
  {
    id: 'la-2',
    pillar: 'Enterprise Scalability',
    questionText: 'How does access to mobile payment infrastructure (merchant QR) affect monthly gross sales in rural youth MSMEs?',
    leadInvestigator: 'Dawit Bekele (MEAL)',
    status: 'Analysis & Synthesis',
    evidenceCollectedSummary: 'Preliminary findings show 42% faster inventory turnover in businesses using Telebirr merchant codes.',
    lastUpdated: '2026-01-28',
  }
];

export const INITIAL_REFLECTION_MEETINGS: ReflectionMeeting[] = [
  {
    id: 'rf-1',
    title: 'Q4 2025 Programme Performance & Learning Reflection',
    type: 'Quarterly MEAL Review',
    date: '2025-12-18',
    venue: 'Skylight Hotel, Addis Ababa / Hybrid',
    participantsCount: 42,
    keyInsights: [
      'Female participation reached 54%, outperforming the 50% target.',
      'Loan disbursement delays occurred in 2 woredas due to manual MFI paperwork.',
      'Fayida ID pilot verified 98% participant unique identity accuracy.'
    ],
    keyActionsAgreed: [
      'Automate MFI loan reporting API before Q2 2026.',
      'Deploy offline mobile field collection app for enumerators in remote woredas.',
      'Enhance disability inclusion recruitment in TVET partnerships.'
    ]
  }
];

export const INITIAL_INDICATORS: Indicator[] = [
  {
    id: 'ind-1',
    code: 'IND-1.1',
    title: 'Number of youth transitioned into dignified and fulfilling work (wage or self-employment)',
    pillar: 'Pillar 1: Youth Employment',
    level: 'Impact',
    baseline: 0,
    targetYear1: 15000,
    targetLifeOfProgramme: 100000,
    actualAchieved: 11450,
    achievementRatePercent: 76.3,
    unit: 'Youth individuals',
    ragStatus: 'On Track',
    disaggregationSex: { female: 6183, male: 5267 },
    lastUpdated: '2026-02-01',
    frequency: 'Monthly',
    dataCollectorRole: 'Field Officer / Monitoring Officer',
  },
  {
    id: 'ind-2',
    code: 'IND-1.2',
    title: 'Percentage of supported youth retaining employment for at least 6 consecutive months',
    pillar: 'Pillar 1: Youth Employment',
    level: 'Outcome',
    baseline: 42,
    targetYear1: 75,
    targetLifeOfProgramme: 85,
    actualAchieved: 71,
    achievementRatePercent: 94.6,
    unit: 'Percentage (%)',
    ragStatus: 'On Track',
    disaggregationSex: { female: 73, male: 69 },
    lastUpdated: '2026-01-30',
    frequency: 'Quarterly',
    dataCollectorRole: 'Monitoring Officer',
  },
  {
    id: 'ind-3',
    code: 'IND-2.1',
    title: 'Number of MSMEs receiving structured business development and market linkage services',
    pillar: 'Pillar 2: Enterprise Ecosystem',
    level: 'Output',
    baseline: 0,
    targetYear1: 1200,
    targetLifeOfProgramme: 8000,
    actualAchieved: 780,
    achievementRatePercent: 65.0,
    unit: 'Enterprises',
    ragStatus: 'At Risk',
    disaggregationSex: { female: 420, male: 360 },
    lastUpdated: '2026-02-03',
    frequency: 'Monthly',
    dataCollectorRole: 'Partner Officer',
  },
  {
    id: 'ind-4',
    code: 'IND-2.2',
    title: 'Average percentage increase in monthly enterprise revenue among supported MSMEs',
    pillar: 'Pillar 2: Enterprise Ecosystem',
    level: 'Outcome',
    baseline: 0,
    targetYear1: 30,
    targetLifeOfProgramme: 50,
    actualAchieved: 26.5,
    achievementRatePercent: 88.3,
    unit: 'Percentage (%)',
    ragStatus: 'On Track',
    disaggregationSex: { female: 28, male: 25 },
    lastUpdated: '2026-01-25',
    frequency: 'Bi-annually',
    dataCollectorRole: 'Monitoring Officer',
  },
  {
    id: 'ind-5',
    code: 'IND-3.1',
    title: 'Total volume of concessionary credit disbursed to youth enterprises by partner MFIs (ETB)',
    pillar: 'Pillar 3: Financial Inclusion',
    level: 'Output',
    baseline: 0,
    targetYear1: 50000000,
    targetLifeOfProgramme: 350000000,
    actualAchieved: 31000000, // 3.1M in demo scale / 31M full scale
    achievementRatePercent: 62.0,
    unit: 'ETB (Millions)',
    ragStatus: 'At Risk',
    disaggregationSex: { female: 17000000, male: 14000000 },
    lastUpdated: '2026-02-01',
    frequency: 'Monthly',
    dataCollectorRole: 'Finance Officer',
  },
  {
    id: 'ind-6',
    code: 'IND-4.1',
    title: 'Percentage of safeguarding complaints acknowledged within 48h and resolved within SLA',
    pillar: 'Cross-Cutting: Safeguarding & Gender',
    level: 'Output',
    baseline: 50,
    targetYear1: 95,
    targetLifeOfProgramme: 100,
    actualAchieved: 91,
    achievementRatePercent: 95.7,
    unit: 'Percentage (%)',
    ragStatus: 'On Track',
    disaggregationSex: { female: 93, male: 89 },
    lastUpdated: '2026-02-04',
    frequency: 'Monthly',
    dataCollectorRole: 'Super Admin / Lead Safeguarding',
  }
];

export const INITIAL_SURVEY_ROUNDS: SurveyRound[] = [
  {
    id: 'srv-1',
    code: 'SRV-BL-2025',
    title: 'Baseline Socio-Economic & Market Assessment',
    type: 'Baseline Survey',
    targetSample: 1200,
    completedSample: 1200,
    startDate: '2025-07-01',
    endDate: '2025-09-30',
    status: 'Closed',
    regionsIncluded: ['Oromia', 'Amhara', 'Sidama', 'Somali', 'Central Ethiopia', 'Addis Ababa', 'Dire Dawa', 'Tigray'],
  },
  {
    id: 'srv-2',
    code: 'SRV-ML-2026',
    title: 'Year 1 Midline Youth Employment & Enterprise Resilience Survey',
    type: 'Midline Survey',
    targetSample: 800,
    completedSample: 340,
    startDate: '2026-01-15',
    endDate: '2026-04-15',
    status: 'Active',
    regionsIncluded: ['Oromia', 'Amhara', 'Sidama', 'Addis Ababa'],
  },
  {
    id: 'srv-3',
    code: 'SRV-RMA-2026',
    title: 'Rapid Green Jobs & Renewable Energy Skills Demand Study',
    type: 'Rapid Market Assessment',
    targetSample: 250,
    completedSample: 185,
    startDate: '2026-02-01',
    endDate: '2026-03-15',
    status: 'Active',
    regionsIncluded: ['Amhara', 'Oromia', 'Tigray'],
  }
];

export const INITIAL_OFFLINE_SURVEYS: OfflineSurveyItem[] = [
  {
    id: 'off-1',
    surveyRoundId: 'srv-2',
    surveyTitle: 'Year 1 Midline Youth Employment Survey',
    respondentName: 'Tadewos Bekele',
    respondentPhone: '+251 91 888 1234',
    region: 'Oromia',
    woreda: 'Bishoftu Kebele 04',
    collectedAt: '2026-02-04 14:22',
    enumeratorName: 'Yared Getachew (Field Officer)',
    deviceSyncStatus: 'Pending Sync',
    payloadSummary: 'Wage employment verified: 7,500 ETB/mo. 18 questions completed.',
  },
  {
    id: 'off-2',
    surveyRoundId: 'srv-2',
    surveyTitle: 'Year 1 Midline Youth Employment Survey',
    respondentName: 'Aster Mulugeta',
    respondentPhone: '+251 92 777 5678',
    region: 'Amhara',
    woreda: 'Bahir Dar Kebele 02',
    collectedAt: '2026-02-04 15:45',
    enumeratorName: 'Tigist Alemu (Field Officer)',
    deviceSyncStatus: 'Pending Sync',
    payloadSummary: 'Self-employment micro-bakery. 18 questions completed.',
  },
  {
    id: 'off-3',
    surveyRoundId: 'srv-3',
    surveyTitle: 'Rapid Green Jobs Demand Study',
    respondentName: 'Girma Wondimu',
    respondentPhone: '+251 93 444 8901',
    region: 'Sidama',
    woreda: 'Hawassa Industrial Area',
    collectedAt: '2026-02-03 11:10',
    enumeratorName: 'Mulugeta T. (Enumerator)',
    deviceSyncStatus: 'Synced',
    payloadSummary: 'Solar PV installation employer survey completed.',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-1',
    timestamp: '2026-02-04 17:30:15',
    userEmail: 'admin@demo.meal.et',
    userName: 'Sami A. (Super Admin)',
    userRole: 'super_admin',
    action: 'LOGIN',
    module: 'Auth',
    description: 'Successful administrative authentication with 2FA token',
    ipAddress: '197.156.104.22',
  },
  {
    id: 'aud-2',
    timestamp: '2026-02-04 16:15:40',
    userEmail: 'programme_manager@demo.meal.et',
    userName: 'Almaz Tadesse',
    userRole: 'programme_manager',
    action: 'UPDATE',
    module: 'Safeguarding',
    description: 'Updated case SG-2026-001 status to Action Plan Underway',
    ipAddress: '197.156.104.30',
  },
  {
    id: 'aud-3',
    timestamp: '2026-02-04 14:05:12',
    userEmail: 'monitoring_officer@demo.meal.et',
    userName: 'Dawit Bekele',
    userRole: 'monitoring_officer',
    action: 'VERIFY',
    module: 'Participants',
    description: 'Verified employment contract for participant p-1 (Almaz Tadesse)',
    ipAddress: '197.156.104.45',
  },
  {
    id: 'aud-4',
    timestamp: '2026-02-03 11:50:00',
    userEmail: 'finance_officer@demo.meal.et',
    userName: 'Bethlehem Alemu',
    userRole: 'finance_officer',
    action: 'CREATE',
    module: 'Finance',
    description: 'Approved loan record LN-2026-OM-0041 for Hiwot Assefa',
    ipAddress: '197.156.104.88',
  }
];

export const INITIAL_GOVERNANCE: GovernanceItem[] = [
  {
    id: 'gov-1',
    title: 'Programme Steering Committee (PSC)',
    body: 'Steering Committee',
    lastMeetingDate: '2026-01-15',
    status: 'Compliant',
    activeResolutionsCount: 5,
    chairPerson: 'State Minister of Labor and Skills / Consortium Co-Chair',
  },
  {
    id: 'gov-2',
    title: 'Technical Advisory Group (TAG)',
    body: 'Technical Advisory Group',
    lastMeetingDate: '2026-01-28',
    status: 'Compliant',
    activeResolutionsCount: 3,
    chairPerson: 'Lead MEAL Advisor',
  },
  {
    id: 'gov-3',
    title: 'Safeguarding & Ethics Oversight Committee',
    body: 'Steering Committee',
    lastMeetingDate: '2026-01-10',
    status: 'Compliant',
    activeResolutionsCount: 2,
    chairPerson: 'Independent Gender & Social Inclusion Specialist',
  }
];
